### PR TITLE
Refactoring data() ... without token

### PR DESCRIPTION
**Pull request by david1983**

### CODE REVIEW

**Comment by pvdsp** [comment]
@yasinS I can confirm that the JavaScript code works perfectly! Can you solve the conflicts and merge to master branch? Thanks.

**Comment by pvdsp** [comment]
@david1983 Great work with the Javascript btw, someone else fixed the CSS but the JavaScript code is a huge plus.

**Comment by yasinS** [comment]
@pvdsp: All done, merged to master!
@david1983: Thanks for the commits and PR :)

**Comment by yasinS** [comment]
@pvdsp Think @JacobJangles' earlier CSS fixes may have been overwritten. Just trying to identify what needs to be revised.

overflow

**Pull request merged**
